### ISSUE TITLE
Make zoom-out functionality center and show the entire map

### ISSUE THREAD

**Issue by nmvecere** [foodtaste-senior-design/StyxAndStones#10]
Example: If you enter the Gauntlet level and zoom out while standing at the starting position, the bottom of the level isn't visible. It should be.

Possible solution: instead of left bumper zooming out, pressing the left bumper snaps to a static view of the entire level.

**Comment by lnn25** [comment]
Zoom-out now can view the entire map in both Cemetery and Gautlet scene.
*New Problem: The main camera are following the character, need to somehow disable this while pressing zoomout button so the camera couldn't follow anymore.

**Comment by lnn25** [comment]
-first solution: freeze the game while zooming to the center based on player location (4 corners):   Using Time.timeScale=0.0f to freeze the game will also freeze the zoom out function
-second solution: use secondary camera that place in the center of the scene: We are having background attached to player, using 2nd camera make it unable to see the background
